export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const SAVE_TEMPORARY_USER_TO_REDUX_STORE = "SAVE_TEMPORARY_USER_TO_REDUX_STORE";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CLEAR_USER_ERRORS = "CLEAR_USER_ERRORS";

export const GET_FIELDS_SUCCESS = "GET_FIELDS_SUCCESS";
export const GET_FIELDS_ERROR = "GET_FIELDS_ERROR";
export const GET_ALL_FIELDS_AT_ONCE = "GET_ALL_FIELDS_AT_ONCE";

export const IS_FIELD_LIST_EMPTY = "IS_FIELD_LIST_EMPTY";

export const GET_MATCHES_SUCCESS = "GET_MATCHES_SUCCESS";
export const GET_MATCHES_ERROR = "GET_MATCHES_ERROR";
export const GET_MY_MATCHES_SUCCESS = "GET_MY_MATCHES_SUCCESS";
export const GET_MY_MATCHES_ERROR = "GET_MY_MATCHES_ERROR";

export const GET_MATCH_SUCCESS = "GET_MATCH_SUCCESS";
export const GET_MATCH_ERROR = "GET_MATCH_ERROR";

export const POST_MATCH_SUCCESS = "POST_MATCH_SUCCESS";
export const POST_MATCH_ERROR = "POST_MATCH_ERROR";